In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(r"C:\Users\Sanju\OneDrive\Desktop\3rd year\DE\cc_state_sector_grads.csv")

In [3]:
df

,index,stateid,state,state_abbr,control,level,year,gender,race,cohort,grad_cohort,grad_100,grad_150,grad_100_rate,grad_150_rate,grad_cohort_ct
0,0,1,Alabama,AL,Private for-profit,4-year,2011,B,A,4y bach,0,0.0,0,NaN,NaN,9
1,1,1,Alabama,AL,Private for-profit,4-year,2011,B,Ai,4y bach,1,0.0,0,0.0,0.0,9
2,2,1,Alabama,AL,Private for-profit,4-year,2011,B,B,4y bach,51,2.0,3,3.9,5.9,9
3,3,1,Alabama,AL,Private for-profit,4-year,2011,B,H,4y bach,1,0.0,0,0.0,0.0,9
4,4,1,Alabama,AL,Private for-profit,4-year,2011,B,W,4y bach,66,15.0,18,22.7,27.3,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
84937,84937,0,United States,US,Public,2-year,2013,M,Ai,2y all,3956,NaN,510,NaN,12.9,926
84938,84938,0,United States,US,Public,2-year,2013,M,B,2y all,53531,NaN,5642,NaN,10.5,926
84939,84939,0,United States,US,Public,2-year,2013,M,H,2y all,54952,NaN,8294,NaN,15.1,926
84940,84940,0,United States,US,Public,2-year,2013,M,W,2y all,200074,NaN,43642,NaN,21.8,926
84941,84941,0,United States,US,Public,2-year,2013,M,X,2y all,361735,NaN,68328,NaN,18.9,926

In [4]:
df.head()

,index,stateid,state,state_abbr,control,level,year,gender,race,cohort,grad_cohort,grad_100,grad_150,grad_100_rate,grad_150_rate,grad_cohort_ct
0,0,1,Alabama,AL,Private for-profit,4-year,2011,B,A,4y bach,0,0.0,0,NaN,NaN,9
1,1,1,Alabama,AL,Private for-profit,4-year,2011,B,Ai,4y bach,1,0.0,0,0.0,0.0,9
2,2,1,Alabama,AL,Private for-profit,4-year,2011,B,B,4y bach,51,2.0,3,3.9,5.9,9
3,3,1,Alabama,AL,Private for-profit,4-year,2011,B,H,4y bach,1,0.0,0,0.0,0.0,9
4,4,1,Alabama,AL,Private for-profit,4-year,2011,B,W,4y bach,66,15.0,18,22.7,27.3,9

In [5]:
df.tail()

,index,stateid,state,state_abbr,control,level,year,gender,race,cohort,grad_cohort,grad_100,grad_150,grad_100_rate,grad_150_rate,grad_cohort_ct
84937,84937,0,United States,US,Public,2-year,2013,M,Ai,2y all,3956,NaN,510,NaN,12.9,926
84938,84938,0,United States,US,Public,2-year,2013,M,B,2y all,53531,NaN,5642,NaN,10.5,926
84939,84939,0,United States,US,Public,2-year,2013,M,H,2y all,54952,NaN,8294,NaN,15.1,926
84940,84940,0,United States,US,Public,2-year,2013,M,W,2y all,200074,NaN,43642,NaN,21.8,926
84941,84941,0,United States,US,Public,2-year,2013,M,X,2y all,361735,NaN,68328,NaN,18.9,926

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 84942 entries, 0 to 84941
Data columns (total 16 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   index           84942 non-null  int64
 1   stateid         84942 non-null  int64
 2   state           84942 non-null  object
 3   state_abbr      84942 non-null  object
 4   control         84942 non-null  object
 5   level           84942 non-null  object
 6   year            84942 non-null  int64
 7   gender          84942 non-null  object
 8   race            84942 non-null  object
 9   cohort          84942 non-null  object
 10  grad_cohort     84942 non-null  int64
 11  grad_100        31760 non-null  float64
 12  grad_150        84942 non-null  int64
 13  grad_100_rate   30033 non-null  float64
 14  grad_150_rate   75623 non-null  float64
 15  grad_cohort_ct  84942 non-null  int64
dtypes: float64(3), int64(6), object(7)
memory usage: 10.4+ MB

In [7]:
df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
84937    False
84938    False
84939    False
84940    False
84941    False
Length: 84942, dtype: bool

In [8]:
df['gender'].nunique()

3

In [9]:
df['state'].unique()[:50]

array(['Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California',
       'Colorado', 'Connecticut', 'Delaware', 'District of Columbia',
       'Florida', 'Georgia', 'Hawaii', 'Idaho', 'Illinois', 'Indiana',
       'Iowa', 'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland',
       'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi',
       'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New Hampshire',
       'New Jersey', 'New Mexico', 'New York', 'North Carolina',
       'North Dakota', 'Ohio', 'Oklahoma', 'Oregon', 'Pennsylvania',
       'Rhode Island', 'South Carolina', 'South Dakota', 'Tennessee',
       'Texas', 'Utah', 'Vermont', 'Virginia', 'Washington',
       'West Virginia', 'Wisconsin'], dtype=object)

In [10]:
df1 = df.drop(columns=['grad_150','grad_100'])

In [11]:
df1.shape

(84942, 14)

In [12]:
df1.head()

,index,stateid,state,state_abbr,control,level,year,gender,race,cohort,grad_cohort,grad_100_rate,grad_150_rate,grad_cohort_ct
0,0,1,Alabama,AL,Private for-profit,4-year,2011,B,A,4y bach,0,NaN,NaN,9
1,1,1,Alabama,AL,Private for-profit,4-year,2011,B,Ai,4y bach,1,0.0,0.0,9
2,2,1,Alabama,AL,Private for-profit,4-year,2011,B,B,4y bach,51,3.9,5.9,9
3,3,1,Alabama,AL,Private for-profit,4-year,2011,B,H,4y bach,1,0.0,0.0,9
4,4,1,Alabama,AL,Private for-profit,4-year,2011,B,W,4y bach,66,22.7,27.3,9

In [13]:
round((df1.isnull().sum()/df1.shape[0])*100,2)

index              0.00
stateid            0.00
state              0.00
state_abbr         0.00
control            0.00
level              0.00
year               0.00
gender             0.00
race               0.00
cohort             0.00
grad_cohort        0.00
grad_100_rate     64.64
grad_150_rate     10.97
grad_cohort_ct     0.00
dtype: float64

In [14]:
df2 = df1.drop(columns='race')

In [15]:
df2.head()

,index,stateid,state,state_abbr,control,level,year,gender,cohort,grad_cohort,grad_100_rate,grad_150_rate,grad_cohort_ct
0,0,1,Alabama,AL,Private for-profit,4-year,2011,B,4y bach,0,NaN,NaN,9
1,1,1,Alabama,AL,Private for-profit,4-year,2011,B,4y bach,1,0.0,0.0,9
2,2,1,Alabama,AL,Private for-profit,4-year,2011,B,4y bach,51,3.9,5.9,9
3,3,1,Alabama,AL,Private for-profit,4-year,2011,B,4y bach,1,0.0,0.0,9
4,4,1,Alabama,AL,Private for-profit,4-year,2011,B,4y bach,66,22.7,27.3,9

In [16]:

df2.dropna(subset=['control'], axis=0, inplace=True)

In [17]:
df2.head()

,index,stateid,state,state_abbr,control,level,year,gender,cohort,grad_cohort,grad_100_rate,grad_150_rate,grad_cohort_ct
0,0,1,Alabama,AL,Private for-profit,4-year,2011,B,4y bach,0,NaN,NaN,9
1,1,1,Alabama,AL,Private for-profit,4-year,2011,B,4y bach,1,0.0,0.0,9
2,2,1,Alabama,AL,Private for-profit,4-year,2011,B,4y bach,51,3.9,5.9,9
3,3,1,Alabama,AL,Private for-profit,4-year,2011,B,4y bach,1,0.0,0.0,9
4,4,1,Alabama,AL,Private for-profit,4-year,2011,B,4y bach,66,22.7,27.3,9

In [18]:
df2.shape

(84942, 13)