In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, mean_squared_error, r2_score
from sklearn import datasets
import warnings
warnings.filterwarnings('ignore')

# Using Iris Datasets

In [2]:
iris = datasets.load_iris()

In [3]:
import pandas as pd
iris_df = pd.DataFrame(iris.data, columns=iris.feature_names)
iris_df.head()

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [4]:
X = iris.data
Y = iris.target

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state= 42)

In [5]:
rf_classifier = RandomForestClassifier(n_estimators=100, random_state=42)

In [6]:
rf_classifier.fit(X_train, Y_train)

RandomForestClassifier(random_state=42)

In [7]:
y_pred = rf_classifier.predict(X_test)

In [8]:
accuracy = accuracy_score(Y_test, y_pred)
classification_rep = classification_report(Y_test, y_pred)

In [9]:
print(f"Accuracy: {accuracy:.2f} ")
print("\nClassification Report:\n", classification_rep)

Accuracy: 1.00

Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

In [10]:
sample = X_test[0:4]
prediction = rf_classifier.predict(sample)

In [11]:
print("predict: \n", prediction)

predict:
 [1 0 2 1]

In [12]:
mse = mean_squared_error(Y_test, y_pred)
print(f"Mean Squared Error: {mse:.2f}")

Mean Squared Error: 0.00

In [13]:
r2 = r2_score(Y_test, y_pred)
print(f"R-squared Score: {r2:.2f}")

R-squared Score: 1.00

# Using Wine Datasets

In [14]:
from sklearn.datasets import load_wine
wine_data = load_wine()

In [16]:
wine_data_df = pd.DataFrame(wine_data.data, wine_data.target)
wine_data_df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0
0,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0
0,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0
0,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0
0,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0

In [17]:
X = wine_data.data
Y= wine_data.target

In [18]:
feature_names = wine_data.feature_names
target_names = wine_data.target_names

In [19]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state= 42)

In [20]:
rf_classifier = RandomForestClassifier(n_estimators=100, random_state=42)

In [21]:
rf_classifier.fit(X_train, Y_train)
y_pred = rf_classifier.predict(X_test)

In [22]:
accuracy = accuracy_score(Y_test, y_pred)
classification_rep = classification_report(Y_test, y_pred)

print(f"Accuracy: {accuracy:.2f} ")
print("\nClassification Report:\n", classification_rep)

Accuracy: 1.00

Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       1.00      1.00      1.00        14
           2       1.00      1.00      1.00         8

    accuracy                           1.00        36
   macro avg       1.00      1.00      1.00        36
weighted avg       1.00      1.00      1.00        36

In [23]:
sample = X_test[0:4]
prediction = rf_classifier.predict(sample)

In [24]:
print("predict: \n", prediction)

predict:
 [0 0 2 0]

In [25]:
mse = mean_squared_error(Y_test, y_pred)
print(f"Mean Squared Error: {mse:.2f}")

r2 = r2_score(Y_test, y_pred)
print(f"R-squared Score: {r2:.2f}")

Mean Squared Error: 0.00
R-squared Score: 1.00